language: php

env:
  - DB_CONNECTION=sqlite

sevices:
  - mysql

php:
  - 5.6
  - 5.5
  - 7.0

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - touch database/database.sqlite
  - composer install
  - php artisan migrate --database=sqlite --force

script:
  - phpunit

# code coverage
before_install:
  - pip install --user codecov
  - mysql -e 'create database homestead;'
after_success:
    - bash <(curl -s https://codecov.io/bash)  
